export default {
	GET_USER:"GET_USER",
	POST_LOGIN:"POST_LOGIN",
	GET_INPUT:"GET_INPUT",
	GET_MESSAGE:"GET_MESSAGE",

	LOGIN_SUCCESS:"LOGIN_SUCCESS",
	LOGIN_FAILURE:"LOGIN_FAILURE",
	LOGIN_REQUEST:"LOGIN_REQUEST",
	LOGOUT_REQUEST:"LOGOUT_REQUEST",

	USER_REQUEST:"USER_REQUEST",
	USER_SUCCESS:"USER_SUCCESS",
	USER_FAILURE:"USER_FAILURE",
};